version: '3.8'

services:
  django:
    build: ./backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - postgre

  postgre:
    image: pgvector/pgvector:pg17
    container_name: postgresql
    env_file: ./backend/autoclean/.env
    volumes:
      - ./postgre/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network1

networks:
  network1:
