# Generated by Django 5.1.2 on 2024-11-08 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_taskprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportScanResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("row", models.IntegerField()),
                ("col", models.IntegerField()),
                ("message", models.CharField(max_length=255)),
                ("cleaner", models.CharField(max_length=255)),
                ("activate", models.BooleanField(default=False)),
                (
                    "import_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_results",
                        to="api.import",
                    ),
                ),
            ],
        ),
    ]
