# Generated by Django 5.1.2 on 2025-02-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_importscanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDataOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('import_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_data_ori', to='api.import')),
            ],
        ),
    ]
