# Generated by Django 5.1.2 on 2025-02-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_importscanresult_activate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Processing'), (3, 'Completed'), (4, 'Failed')], default=1),
        ),
    ]
