# Generated by Django 5.1.2 on 2025-02-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_import_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fn_name', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('definition', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
