# Generated by Django 5.1.2 on 2025-03-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cleaner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='importscanresult',
            name='priority',
            field=models.IntegerField(db_index=True, default=1000),
        ),
    ]
