# Generated by Django 5.1.2 on 2025-02-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_importdataoriginal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importscanresult',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='importscanresult',
            name='cleaner',
        ),
        migrations.AddField(
            model_name='importscanresult',
            name='action_type',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImportScanResultAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cleaner', models.CharField(blank=True, max_length=255, null=True)),
                ('cleaner_id', models.IntegerField(blank=True, null=True)),
                ('activate', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('import_scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.importscanresult')),
            ],
        ),
    ]
